services:
  front:
    build:
      context: ./front-app
      dockerfile: Dockerfile
    container_name: front
    ports:
      - '3000'
    stdin_open: true
    networks:
      - buypilot-network
  fastapi:
    build:
      context: ./TFG
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - '8000'
    networks:
      - buypilot-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BuyPilot
      MYSQL_USER: buypilot
      MYSQL_PASSWORD: buypilot23
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - buypilot-network
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front
      - fastapi
    networks:
      - buypilot-network
volumes:
  mysql_data:

networks:
  buypilot-network:
    driver: bridge
